// QuantumProof API Client - Connects to REAL FHE backend

const API_BASE = 'http://localhost:5001/api';

/**
 * Check if FHE backend is available
 */
export async function checkStatus() {
  try {
    const response = await fetch(`${API_BASE}/status`);
    if (!response.ok) throw new Error('Backend not available');
    return await response.json();
  } catch (error) {
    console.error('Backend status check failed:', error);
    throw new Error('Cannot connect to FHE backend. Make sure the API server is running.');
  }
}

/**
 * Run REAL FHE computation on backend
 */
export async function runQuantumProof({ sensitiveInput, scenario, forceFallback }) {
  try {
    const response = await fetch(`${API_BASE}/compute`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        sensitiveInput,
        scenario,
        forceFallback,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Computation failed');
    }

    const data = await response.json();

    if (!data.success) {
      throw new Error(data.error || 'Computation failed');
    }

    // Transform backend response to match frontend format
    const result = data.result;

    return {
      runId: result.run_id,
      timestampUtc: result.timestamp_utc,
      scenario: result.scenario,
      riskContext: result.risk_context,
      trustModelComparison: result.trust_model_comparison,
      computeResult: {
        riskReductionPercent: result.compute_result.risk_reduction_percent,
        performanceOverheadPercent: result.compute_result.performance_overhead_percent,
        recommendedRollout: result.compute_result.recommended_rollout,
        fheEnabled: result.compute_result.fhe_enabled || false,
        fheScheme: result.compute_result.fhe_scheme || 'N/A',
      },
      benchmark: {
        runtimeMs: result.benchmark.runtime_ms,
        computeMode: result.benchmark.compute_mode,
        encryptionTimeMs: result.benchmark.encryption_time_ms,
        computationTimeMs: result.benchmark.computation_time_ms,
        proofTimeMs: result.benchmark.proof_time_ms,
      },
      proof: {
        proofHash: result.proof.proof_hash,
        verificationResult: result.proof.verification_result,
        circuitVersion: result.proof.circuit_version,
        inputFingerprint: result.proof.input_fingerprint,
        cryptoPrimitivesUsed: result.proof.crypto_primitives_used || [],
        fheParameters: result.proof.fhe_parameters || {},
      },
    };
  } catch (error) {
    console.error('FHE computation error:', error);
    throw error;
  }
}

/**
 * Convert report to Markdown
 */
export function toMarkdown(report) {
  const primitivesList = (report.proof.cryptoPrimitivesUsed || [])
    .map(p => `  - ${p}`)
    .join('\n');

  return `# QuantumProof Ops - FHE Computation Report

## Run Metadata
- **Run ID**: \`${report.runId}\`
- **Timestamp**: \`${report.timestampUtc}\`
- **Scenario**: \`${report.scenario}\`
- **Verification**: \`${report.proof.verificationResult ? '✅ VERIFIED' : '❌ FAILED'}\`

## Cryptographic Primitives
${primitivesList}

## FHE Parameters
\`\`\`json
${JSON.stringify(report.proof.fheParameters, null, 2)}
\`\`\`

## Results
- **Risk Score**: \`${report.computeResult.riskReductionPercent}%\`
- **FHE Overhead**: \`${report.computeResult.performanceOverheadPercent}%\`
- **FHE Enabled**: \`${report.computeResult.fheEnabled}\`
- **FHE Scheme**: \`${report.computeResult.fheScheme}\`

## Performance
- **Total Runtime**: \`${report.benchmark.runtimeMs}ms\`
- **Encryption Time**: \`${report.benchmark.encryptionTimeMs}ms\`
- **Computation Time**: \`${report.benchmark.computationTimeMs}ms\`
- **Proof Generation**: \`${report.benchmark.proofTimeMs}ms\`

## Quantum-Risk Context

${report.riskContext}

## Trust Model Comparison

${report.trustModelComparison}

## Audit Trail
- **ZK Proof Hash**: \`${report.proof.proofHash}\`
- **Input Fingerprint**: \`${report.proof.inputFingerprint}\`
- **Circuit Version**: \`${report.proof.circuitVersion}\`

---
*Generated by QuantumProof Ops using REAL Microsoft SEAL FHE*
`;
}

/**
 * Download file to user's computer
 */
export function downloadFile(filename, content, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
